### ISSUE TITLE
Opening index.html instruction should be presented in earlier lessons

### ISSUE THREAD

**Issue by zolkocarbon** [learn-co-curriculum/listening-to-dom-nodes#14]
This lab, Listening To Nodes, starts off by showing you how to open the index.html by manually forking it to IDE and then how to open it in the browser.

This information should be presented in the Creating and Inserting Nodes lesson which is two lessons earlier than this one. An index.html file is also being used in that lesson. 
<img width="361" alt="screen shot 2017-08-06 at 8 52 43 am" src="https://user-images.githubusercontent.com/25081806/29003425-bedc845c-7a84-11e7-9307-9b5045422f98.png">
<img width="544" alt="screen shot 2017-08-06 at 8 52 56 am" src="https://user-images.githubusercontent.com/25081806/29003426-bee2d53c-7a84-11e7-966e-e24600d6985a.png">

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
