### ISSUE TITLE
Incorrect Code in 'PREVENTING THE DEFAULT BEHAVIOR'

### ISSUE THREAD

**Issue by djlowes** [learn-co-curriculum/listening-to-dom-nodes#15]
**Code reads:**

````
const input = document.querySelector('input')
 
input.addEventListener('keydown', function(e) {
  if (e.which === 71) {
    return e.preventDefault()
  }
})
````

**It should read:**

````
const input = document.querySelector('input')
 
input.addEventListener('keydown', function(e) {
  if (e.which === 71) {
    return e.preventDefault()
  } else {
console.log(e.which)
}
})
````

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
