### ISSUE TITLE
Is the initial instructions on forking and cloning the repository necessary?

### ISSUE THREAD

**Issue by epunx2** [learn-co-curriculum/listening-to-dom-nodes#16]
Hi, the online learn.co ide environment automatically forks and clones the repositories for me. I received instructions at the beginning of this lab to do this manually. That was actually helpful but, I don't know if that was necessary since it happens automatically. I attached a screenshot
![screen shot 2018-03-14 at 8 52 36 pm](https://user-images.githubusercontent.com/14227328/37440261-e800dff2-27c9-11e8-90d4-1658c84e9918.png)

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
