### ISSUE TITLE
Sentence doesn't make sense in How to Manually Open a Lab

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/listening-to-dom-nodes#17]
This sentence doesn't make sense:
And look got the button at the top that will bring you to the lab's GitHub page.
Here is the link for that sentence:
http://help.learn.co/workflow-tips/learn-gem/how-to-manually-open-a-lab

Thank you.

**Comment by drakeltheryuujin** [comment]
Hi @ValerieHMoore,
Thanks for you feedback. A ticket has been logged for the support team to address this issue.
💙
