### ISSUE TITLE
No index.html file 

### ISSUE THREAD

**Issue by Daniellaguips** [learn-co-curriculum/listening-to-dom-nodes#18]
Hello! :)

When I run httpserver and try to open index.html (as I am told to do on instructions) I have index.js but not html file. 

<img width="1280" alt="screen shot 2018-07-17 at 4 33 34 pm" src="https://user-images.githubusercontent.com/20194448/42843834-36fbadc2-89df-11e8-8fc6-085566028f07.png">

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
