### ISSUE TITLE
"Open IDE" not available

### ISSUE THREAD

**Issue by nsfphd** [learn-co-curriculum/listening-to-dom-nodes#19]
The text suggests Open IDE should be available to pull the index.html file and run it from httpserver, but only the Sandbox is visible..

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
