### ISSUE TITLE
Listening To Nodes Lab

### ISSUE THREAD

**Issue by jeff-gosselin** [learn-co-curriculum/listening-to-dom-nodes#20]
index.html file is missing when I use httpserver to copy IP address from terminal and paste it in my browser. 
![capture](https://user-images.githubusercontent.com/42256814/44369787-9d467680-a4a5-11e8-9a83-6c90e805beb9.PNG)

**Comment by cnezames** [comment]
It took me awhile to figure out as well. You have to clone the repository from GitHub and open it in Learn.  There is a tutorial here: https://learn.co/lessons/forks-and-clones-readme

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
