### ISSUE TITLE
Lesson assumes we have 'Open IDE' button but only 'Sandbox'

### ISSUE THREAD

**Issue by cwgabel** [learn-co-curriculum/listening-to-dom-nodes#21]
listening-to-dom-nodes lesson

The introduction seems to suggest that I can just click on the Learn IDE (via Open IDE button) option which I don't have.

I had this issue on the previous lesson as well where it asked me to open the lesson's index.html file that must be also in the Learn IDE but I don't know how to access it when all the lesson has available is a sandbox. 

This is all very confusing, so maybe it's me.  Sorry in advance if there is a button I just don't see on the screen.

**Comment by cnezames** [comment]
I had issues too.  There is a tutorial here:
https://learn.co/lessons/forks-and-clones-readme

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#24.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
