### ISSUE TITLE
Typo, and suggestion for instructions to be moved to previous lesson

### ISSUE THREAD

**Issue by sqwisha** [learn-co-curriculum/listening-to-dom-nodes#22]
> "Copy this string of numbers, open a new tab and **paste** _(not past)_ the string in to the URL bar."

This whole paragraph would've been immensely helpful in the Hide and Seek lab.

> "If you are using the Learn IDE available in your browser, you will automatically clone down the files you need when you click 'Open IDE', but in order to view index.html, you will need to use httpserver to serve the HTML page temporarily. In the terminal, type httpserver and press enter. You will see that Your server is running at ... followed by a string of numbers and dots. This string is a temporary IP address that is hosting your index.html file. Copy this string of numbers, open a new tab and paste the string in to the URL bar."

Thanks

**Comment by drakeltheryuujin** [comment]
Hi @sqwisha 
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
