### ISSUE TITLE
KeyboardEvent.which is deprecated

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/listening-to-dom-nodes#25]
KeyboardEvent.which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which)

This should be updated to use the [KeyboardEvent.key property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

#Staff

**Comment by sgharms** [comment]
Fixed in #26 

@AspenJames can you review the proposed change in #26 ? If approved, we'll merge.
