### ISSUE TITLE
Readme assumes a follow-along file

### ISSUE THREAD

**Issue by maxgrok** [learn-co-curriculum/listening-to-dom-nodes#4]
This readme presumes a follow along file that does not exist and the lesson is not listed as a lab.

**Comment by AnnJohn** [comment]
hi @maxgrok if you click the github icon (the first of four icons in the upper right corner) of Learn, you'll  be able to open the lesson in Github and you will be able to access the index.html file there. thanks

**Comment by maxgrok** [comment]
Thanks for the quick response!
