### ISSUE TITLE
HTML has no content?

### ISSUE THREAD

**Issue by davidheis** [learn-co-curriculum/listening-to-dom-nodes#7]
It says 'Let's start by adding a listener for click events to the main#main element in index.html'

But there is no content in the HTML. Are we supposed to create the content ourselves beforehand?

**Comment by aturkewi** [comment]
Hey @davidheis I'm not sure I see what you're talking about here. I'm looking at the lab and it looks like the HTML does have content: https://github.com/learn-co-curriculum/listening-to-dom-nodes/blob/master/index.html
Are you seeing something different?

**Comment by JessRudder** [comment]
Going to close this issue due to lack of reproducibility.  Feel free to re-open it if you have more detail to provide.
