### ISSUE TITLE
SyntaxError: redeclaration of const divs

### ISSUE THREAD

**Issue by RuffianX** [learn-co-curriculum/listening-to-dom-nodes#9]
In the section on capturing, the expected result includes, "5 bubbled # you won't see this if you refreshed the page".

But you won't see any of it, because if you don't refresh the page after running the 'bubbling' code you get a syntax error for trying to re-declare the const variable 'divs'. 

Students should be instructed to refresh the page before entering the 'captured' code and the "5 bubbled # you won't see this if you refreshed the page" should be removed from the expected result.

Or the code could be changed to: 

```
let divs = document.querySelectorAll('div')
 
function bubble(e) {
  // remember all of those fancy DOM node properties?
  // we're making use of them to get the number
  // in each div here!
 
  // if `this` is a bit confusing, don't worry —
  // for now, know that it refers to the div that
  // is triggering the current event handler.
  console.log(this.firstChild.nodeValue.trim() + ' bubbled')
}
 
for (let i = 0, l = divs.length; i < l; i++) {
  divs[i].addEventListener('click', bubble)
}
```

and 

```
 divs = document.querySelectorAll('div')
 
function capture(e) {
  console.log(this.firstChild.nodeValue.trim() + ' captured')
}
 
for (let i = 0, l = divs.length; i < l; i++) {
  // set the third argument to `true`!
  divs[i].addEventListener('click', capture, true)
}
```
Then the output will be: 

1 captured 
2 captured 
3 captured 
4 captured 
5 bubbled 
5 captured 
4 bubbled 
3 bubbled 
2 bubbled 
1 bubbled

**Comment by gj** [comment]
Updated — thanks @RuffianX !
